#Localhost | Running on port 3000
##Local Deployment


##getAll Employee Info
GET http://localhost:3000/employees

###getAll Expenses Data
GET http://localhost:3000/expenses      

### getSingle employee info by id
GET http://localhost:3000/employees/67f49b77a86a09bae533a45e

### getSingle expenses data by id
GET http://localhost:3000/expenses/67e1519d7e6ca89b6791efa7

### Add employee info 
POST http://localhost:3000/employees HTTP/1.1
content-type: application/json
  {
    "firstName": "Matthew",
    "lastName": "John Doe",
    "birthDay": null,
    "email": "jaelwilde@gmail.com",
    "department": "Administrative",
    "appointedDate": null,
    "salary": "4,000.00"
  }

### Add expenses Data
POST http://localhost:3000/expenses HTTP/1.1
content-type: application/json

{
  "expenseName": "Rice",
  "expenseCategory": "Food",
  "amountSpent": "20.00",
  "date": "2/04/2025"
}

### Update Employee Info by id
PUT http://localhost:3000/employees/67f49b77a86a09bae533a45e HTTP/1.1
content-type: application/json

{
"firstName": "Robertson",
"lastName": "Dotse",
"birthDay": "11/11/2011",
"email": "raphael@gmail.com",
"department": "Administrative",
"appointmentDate": "01/12/2024",
"salary": "4,000.00"
}

### Update Expenses data by id
PUT http://localhost:3000/expenses/67e1519d7e6ca89b6791efa7 HTTP/1.1
content-type: application/json

{
  "expenseName": "Oil",
  "expenseCategory": "Food",
  "amountSpent": "20.00",
  "date": "2/04/2025"
}



### DELETE Employee Info
DELETE http://localhost:3000/employees/67f49b77a86a09bae533a45e HTTP/1.1

### DELETE expenses data by id
DELETE http://localhost:3000/expenses/67e1519d7e6ca89b6791efa7 HTTP/1.1






// Render.com production Deployment
### Get all employees
GET https://crud-practice-jtlg.onrender.com/employees


### Get all expenses
GET https://crud-practice-jtlg.onrender.com/expenses

### Get employees by id
GET https://crud-practice-jtlg.onrender.com/employees/67e18078fc5fbe68374dc268


### Get expenses by id
GET https://crud-practice-jtlg.onrender.com/expenses/67e1519d7e6ca89b6791efa7


### Add Employees Info
POST https://crud-practice-jtlg.onrender.com/employees HTTP/1.1
content-type: application/json

{
"firstName": "#",
"lastName": "#",
"birthDay": "#",
"email": "#",
"department": "#",
"appointmentDate": "#",
"salary": "#",
"qualification": "#",
"function": "#"
}


### Add Expenses Data
POST https://crud-practice-jtlg.onrender.com/expenses HTTP/1.1
content-type: application/json

{
  "name": "Gasoline",
  "category": "Transportation",
  "date": "20/03/2025",
  "amount": "50.00",
  "month": "#",
  "day": "#",
  "paymentType": "#"
}

### Update Employee Info
PUT https://crud-practice-jtlg.onrender.com/67e1519d7e6ca89b6791efa HTTP/1.1
content-type: application/json

{
"firstName": "#",
"lastName": "#",
"birthDay": "#",
"email": "#",
"department": "#",
"appointmentDate": "#",
"salary": "#",
"qualification": "#",
"function": "#"
}

### Update Expenses Data
PUT https://crud-practice-jtlg.onrender.com/expenses/67e1519d7e6ca89b6791efa7 HTTP/1.1
content-type: application/json

{
  "name": "Gasoline",
  "category": "Transportation",
  "date": "20/03/2025",
  "amount": "100.00",
  "month": "#",
  "day": "#",
  "paymentType": "#"
}

### DELETE Employee Info
DELETE https://crud-practice-jtlg.onrender.com/employees/67e18078fc5fbe68374dc268 HTTP/1.1

### DELETE Expenses Data
DELETE https://crud-practice-jtlg.onrender.com/expenses/67e1519d7e6ca89b6791efa7 HTTP/1.1